# Configuration de base de votre documentation
site_name: Dynasty8
repo_name: Jefedi/ImmoWiki
repo_url: https://github.com/Jefedi/ImmoWiki
nav:
    - Accueil: index.md

# Configuration du thème
theme:
    language: fr
    name: material
    logo: assets/dynasty8.svg
    features:
        - navigation.footer
        - content.action.edit
    icon:
        repo: fontawesome/brands/github
    palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/aESdYg2uFm



plugins:
  - search
  - blog:
      enabled: true
      blog_dir: blog
      post_dir: "{blog}/articles"
      post_date_format: long
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 10



copyright: Copyright &copy; 2025 - 2025 Jefe