site_name: dynasty8
site_url: https://dynasty.jefe.ovh
theme:
  name: material

nav:
  - Accueil: docs/index.md
  
  




















# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json